### ISSUE TITLE
Metadata in results from SQL query does not provide tag key info

### ISSUE THREAD

**Issue by wolffcm** [influxdata/influxdb_iox#3459]
Inserting data into the database with LP like this:
```
t,foo=bar int_field=0  1465839830100400200
...
```
Then if I run this query `select * from t`, I get back a result from the Go client in https://github.com/influxdata/influxdb_iox with the following schema:
```
schema:
    fields: 3
        - foo: type=utf8, nullable
        - int_field: type=int64, nullable
            metadata: ["iox::column::type": "iox::column_type::field::integer"]
        - time: type=timestamp[ns]
            metadata: ["iox::column::type": "iox::column_type::timestamp"]
```
I would expect that field `foo` would have metadata `["iox::column::type": "iox::column_type::tag"]` or something like that.

This is important for Flux to be able to access data via IOx so that we know which columns are in the group key.

For a more thorough reproducer modify this test case:
https://github.com/influxdata/influxdb-iox-client-go/blob/725f09aa0ddfc6d0226da8c981f89bc74643b248/iox_client_test.go#L46

(just change the query to `select * from t` and get the schema with `reader.Schema()`)
