### ISSUE TITLE
Design faster / improve Deduplication 

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#7706]
__Use case:__
IOx contains a custom "deduplicate" operation in its query engine that handles resolving data that runs on all data that has not been "fully" compacted.

This deduplicate operation runs during queries whenever the data hasn't been fully compacted

While improving the compactor (such as #5386) may help there will still be times when the deduplicator needs to run, so making this operation as fast as possible will help query performance

Here is an example of this operator in action
```
DeduplicateExec: <--- this often takes a significant portion of the time                                                                                                                                                                                                 
 SortPreservingMergeExec:                                                                                                                                                              
   SortExec                                                                                                                                                                          
     CoalesceBatchesExec: target_batch_size=8192                                                                                                                                                                                                                                                                                                   
       FilterExec: orgID@6 = 85506640d4e47a10 AND source@9 != tasks AND time@10 > 1682704976590233563 AND (time@10 < -9223372036854775808 OR time@10 > 1670608981592043555)                                                                                                                                                                        
         RecordBatchesExec: batches_groups=3 batches=7 total_rows=71579                                                                                                                                                                                                                                                                           
```

April 2023 performance analysis documents that show deduplicate taking significant time:
1. https://docs.google.com/document/d/1Ba15-iQ-clkz6rxez30Ni034__LP2F7GtW5hIDF26kc/edit#heading=h.hc8iq71wne1a
2 https://docs.google.com/document/d/1qjImorGMzHbdhaWqI_sd_rSLD7aKIQtdx0R5KMD733c/edit#


__Proposal:__
This ticket tracks creating a  plan for how to speed up Deduplication (maybe it is upstream in arrow-rs, maybe it is in DataFusion, maybe it is in IOx, likely in all three)

Here is a previous idea from @tustvold that may be related: https://github.com/influxdata/influxdb_iox/issues/3899
